# Generated by Django 4.0.3 on 2022-03-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carentApi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_model',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='image_interior',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='car_model',
            name='image_rear',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
